// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualWardrobe_ClothesTypes.Data;

#nullable disable

namespace VirtualWardrobe_ClothesTypes.Migrations
{
    [DbContext(typeof(ClothesTypeDbContext))]
    [Migration("20260405140724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VirtualWardrobe_ClothesTypes.Model.ClothesLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClothesLayers");
                });

            modelBuilder.Entity("VirtualWardrobe_ClothesTypes.Model.ClothesType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LayerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClothesTypes");
                });

            modelBuilder.Entity("VirtualWardrobe_ClothesTypes.Model.ClothesType", b =>
                {
                    b.HasOne("VirtualWardrobe_ClothesTypes.Model.ClothesLayer", "Layer")
                        .WithMany("ClothesTypes")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("VirtualWardrobe_ClothesTypes.Model.ClothesLayer", b =>
                {
                    b.Navigation("ClothesTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
